language: node_js
node_js:
  - 8
  - 6

install: yarn install --ignore-engines

branches:
  only:
    - "master"

cache:
  yarn: true
  directories:
  - node_modules

after_script:
  - npm run coveralls

jobs:
  include:
    - stage: release
      node_js: 8
      script: skip
      after_script:
        - git config user.email "nordnet-release@localhost"
        - git config user.name "nordnet-release"
        - TRAVIS_JOB_NUMBER=WORKAROUND.1 npm run travis-deploy-once "npm run semantic-release"
      if: (NOT type IN (pull_request)) AND (branch = master)

stages:
  - test
  - name: release